Import('*')

SimObject('CxlMemory.py', sim_objects=['CxlMemory'])
SimObject('CxlBridge.py', sim_objects=['CxlBridge'])

Source('memory.cc')
Source('bridge.cc')

DebugFlag('CxlMemory', "For CXL Memory")
DebugFlag('CxlBridge', "For CXL Bridge")
